set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'rust-lang/rust.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
" Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
" Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
" Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"
" Make Vim more useful
set nocompatible
" Set color scheme
colo torte
set background=dark
syntax on
set nu

set autoread
set ruler
set cmdheight=2

set expandtab
set smarttab
set shiftwidth=4
set tabstop=4

set wildmenu
set backupdir=~/.vim/backups
set directory=~/.vim/swaps
set viminfo='10,\"100,:20,%,n~/.viminfo

set viminfo+=!
set wmh=0
set hlsearch
set incsearch
set laststatus=2
set modeline
set modelines=4
set noerrorbells
set nostartofline
set ruler
set showmode
set title
set showcmd

if has("autocmd")
    au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Tweaks
" Orange line numbers
" highlight linenr ctermfg=94
highlight linenr ctermfg=darkyellow
highlight statement ctermfg=white
highlight identifier ctermfg=gray
highlight constant ctermfg=darkred
highlight comment ctermfg=darkcyan
